services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - ORIGIN=http://localhost:8080
    volumes:
      - .:/opt/app